### ISSUE TITLE
Add a license

### ISSUE THREAD

**Issue by jubianchi** [atoum/stubs#13]
We should have a license and it should be the same as the atoum/atoum repository
- [x] a `LICENSE` file: it should be the same as the atoum/atoum repository but every mention to "Frédéric Hardy" must be replaced with "atoum contributors"
- [x] in the `composer.json` file (`BSD-3-Clause`)
- [x] in the  `README.md` file: a dedicated section (see [here](https://github.com/atoum/blackfire-extension/blob/master/README.md#licence) for an example)

**Comment by sbshah97** [comment]
Is this issue still open? @jubianchi
