### ISSUE TITLE
Some doc about how to update this?

### ISSUE THREAD

**Issue by Grummfy** [atoum/stubs#21]
Hello,
it could be intresting to have a small explanation on how we can update this repository to add new missing methods

**Comment by Grummfy** [comment]
ping @Hywan @jubianchi  @agallou

**Comment by jubianchi** [comment]
There is not real process to follow. 

This library is simply code, commented with PHP docblock. To update the stubs we just have to add the missing annotations and tag a release.

**Comment by Grummfy** [comment]
thanks. So we have no tools like in the old stub-generator? I think it could be interesting to add one.
